// This file is complitely generated

#ifndef GODOT_TYPES_GEN_H
#define GODOT_TYPES_GEN_H

#include "godot_types_macro.h"
#include "godot_all_includes.h"

MAKE_NATIVE_TYPE_FACTORY(Object)

DAS_BIND_ENUM_CAST(Object::ConnectFlags)
DAS_BASE_BIND_ENUM_SAFE(Object::ConnectFlags, Object`ConnectFlags, Object_ConnectFlags, CONNECT_DEFERRED, CONNECT_PERSIST, CONNECT_ONE_SHOT, CONNECT_REFERENCE_COUNTED)

MAKE_NATIVE_TYPE_FACTORY(Node)

DAS_BIND_ENUM_CAST(Node::ProcessMode)
DAS_BASE_BIND_ENUM_SAFE(Node::ProcessMode, Node`ProcessMode, Node_ProcessMode, PROCESS_MODE_INHERIT, PROCESS_MODE_PAUSABLE, PROCESS_MODE_WHEN_PAUSED, PROCESS_MODE_ALWAYS, PROCESS_MODE_DISABLED)

DAS_BIND_ENUM_CAST(Node::ProcessThreadGroup)
DAS_BASE_BIND_ENUM_SAFE(Node::ProcessThreadGroup, Node`ProcessThreadGroup, Node_ProcessThreadGroup, PROCESS_THREAD_GROUP_INHERIT, PROCESS_THREAD_GROUP_MAIN_THREAD, PROCESS_THREAD_GROUP_SUB_THREAD)

DAS_BIND_ENUM_CAST(Node::ProcessThreadMessages)
DAS_BASE_BIND_ENUM_SAFE(Node::ProcessThreadMessages, Node`ProcessThreadMessages, Node_ProcessThreadMessages, FLAG_PROCESS_THREAD_MESSAGES, FLAG_PROCESS_THREAD_MESSAGES_PHYSICS, FLAG_PROCESS_THREAD_MESSAGES_ALL)

DAS_BIND_ENUM_CAST(Node::DuplicateFlags)
DAS_BASE_BIND_ENUM_SAFE(Node::DuplicateFlags, Node`DuplicateFlags, Node_DuplicateFlags, DUPLICATE_SIGNALS, DUPLICATE_GROUPS, DUPLICATE_SCRIPTS, DUPLICATE_USE_INSTANTIATION)

DAS_BIND_ENUM_CAST(Node::InternalMode)
DAS_BASE_BIND_ENUM_SAFE(Node::InternalMode, Node`InternalMode, Node_InternalMode, INTERNAL_MODE_DISABLED, INTERNAL_MODE_FRONT, INTERNAL_MODE_BACK)

MAKE_NATIVE_TYPE_FACTORY(Timer)

DAS_BIND_ENUM_CAST(Timer::TimerProcessCallback)
DAS_BASE_BIND_ENUM_SAFE(Timer::TimerProcessCallback, Timer`TimerProcessCallback, Timer_TimerProcessCallback, TIMER_PROCESS_PHYSICS, TIMER_PROCESS_IDLE)

MAKE_NATIVE_TYPE_FACTORY(CanvasItem)

DAS_BIND_ENUM_CAST(CanvasItem::TextureFilter)
DAS_BASE_BIND_ENUM_SAFE(CanvasItem::TextureFilter, CanvasItem`TextureFilter, CanvasItem_TextureFilter, TEXTURE_FILTER_PARENT_NODE, TEXTURE_FILTER_NEAREST, TEXTURE_FILTER_LINEAR, TEXTURE_FILTER_NEAREST_WITH_MIPMAPS, TEXTURE_FILTER_LINEAR_WITH_MIPMAPS, TEXTURE_FILTER_NEAREST_WITH_MIPMAPS_ANISOTROPIC, TEXTURE_FILTER_LINEAR_WITH_MIPMAPS_ANISOTROPIC, TEXTURE_FILTER_MAX)

DAS_BIND_ENUM_CAST(CanvasItem::TextureRepeat)
DAS_BASE_BIND_ENUM_SAFE(CanvasItem::TextureRepeat, CanvasItem`TextureRepeat, CanvasItem_TextureRepeat, TEXTURE_REPEAT_PARENT_NODE, TEXTURE_REPEAT_DISABLED, TEXTURE_REPEAT_ENABLED, TEXTURE_REPEAT_MIRROR, TEXTURE_REPEAT_MAX)

DAS_BIND_ENUM_CAST(CanvasItem::ClipChildrenMode)
DAS_BASE_BIND_ENUM_SAFE(CanvasItem::ClipChildrenMode, CanvasItem`ClipChildrenMode, CanvasItem_ClipChildrenMode, CLIP_CHILDREN_DISABLED, CLIP_CHILDREN_ONLY, CLIP_CHILDREN_AND_DRAW, CLIP_CHILDREN_MAX)

MAKE_NATIVE_TYPE_FACTORY(Node2D)

MAKE_NATIVE_TYPE_FACTORY(Sprite2D)

MAKE_NATIVE_TYPE_FACTORY(Area2D)

DAS_BIND_ENUM_CAST(Area2D::SpaceOverride)
DAS_BASE_BIND_ENUM_SAFE(Area2D::SpaceOverride, Area2D`SpaceOverride, Area2D_SpaceOverride, SPACE_OVERRIDE_DISABLED, SPACE_OVERRIDE_COMBINE, SPACE_OVERRIDE_COMBINE_REPLACE, SPACE_OVERRIDE_REPLACE, SPACE_OVERRIDE_REPLACE_COMBINE)

MAKE_NATIVE_TYPE_FACTORY(Label)

MAKE_NATIVE_TYPE_FACTORY(Window)

DAS_BIND_ENUM_CAST(Window::Mode)
DAS_BASE_BIND_ENUM_SAFE(Window::Mode, Window`Mode, Window_Mode, MODE_WINDOWED, MODE_MINIMIZED, MODE_MAXIMIZED, MODE_FULLSCREEN, MODE_EXCLUSIVE_FULLSCREEN)

DAS_BIND_ENUM_CAST(Window::Flags)
DAS_BASE_BIND_ENUM_SAFE(Window::Flags, Window`Flags, Window_Flags, FLAG_RESIZE_DISABLED, FLAG_BORDERLESS, FLAG_ALWAYS_ON_TOP, FLAG_TRANSPARENT, FLAG_NO_FOCUS, FLAG_POPUP, FLAG_EXTEND_TO_TITLE, FLAG_MOUSE_PASSTHROUGH, FLAG_MAX)

DAS_BIND_ENUM_CAST(Window::ContentScaleMode)
DAS_BASE_BIND_ENUM_SAFE(Window::ContentScaleMode, Window`ContentScaleMode, Window_ContentScaleMode, CONTENT_SCALE_MODE_DISABLED, CONTENT_SCALE_MODE_CANVAS_ITEMS, CONTENT_SCALE_MODE_VIEWPORT)

DAS_BIND_ENUM_CAST(Window::ContentScaleAspect)
DAS_BASE_BIND_ENUM_SAFE(Window::ContentScaleAspect, Window`ContentScaleAspect, Window_ContentScaleAspect, CONTENT_SCALE_ASPECT_IGNORE, CONTENT_SCALE_ASPECT_KEEP, CONTENT_SCALE_ASPECT_KEEP_WIDTH, CONTENT_SCALE_ASPECT_KEEP_HEIGHT, CONTENT_SCALE_ASPECT_EXPAND)

DAS_BIND_ENUM_CAST(Window::ContentScaleStretch)
DAS_BASE_BIND_ENUM_SAFE(Window::ContentScaleStretch, Window`ContentScaleStretch, Window_ContentScaleStretch, CONTENT_SCALE_STRETCH_FRACTIONAL, CONTENT_SCALE_STRETCH_INTEGER)

DAS_BIND_ENUM_CAST(Window::LayoutDirection)
DAS_BASE_BIND_ENUM_SAFE(Window::LayoutDirection, Window`LayoutDirection, Window_LayoutDirection, LAYOUT_DIRECTION_INHERITED, LAYOUT_DIRECTION_LOCALE, LAYOUT_DIRECTION_LTR, LAYOUT_DIRECTION_RTL)

DAS_BIND_ENUM_CAST(Window::WindowInitialPosition)
DAS_BASE_BIND_ENUM_SAFE(Window::WindowInitialPosition, Window`WindowInitialPosition, Window_WindowInitialPosition, WINDOW_INITIAL_POSITION_ABSOLUTE, WINDOW_INITIAL_POSITION_CENTER_PRIMARY_SCREEN, WINDOW_INITIAL_POSITION_CENTER_MAIN_WINDOW_SCREEN, WINDOW_INITIAL_POSITION_CENTER_OTHER_SCREEN, WINDOW_INITIAL_POSITION_CENTER_SCREEN_WITH_MOUSE_FOCUS, WINDOW_INITIAL_POSITION_CENTER_SCREEN_WITH_KEYBOARD_FOCUS)

MAKE_NATIVE_TYPE_FACTORY(Resource)

MAKE_NATIVE_TYPE_FACTORY(PackedScene)

DAS_BIND_ENUM_CAST(PackedScene::GenEditState)
DAS_BASE_BIND_ENUM_SAFE(PackedScene::GenEditState, PackedScene`GenEditState, PackedScene_GenEditState, GEN_EDIT_STATE_DISABLED, GEN_EDIT_STATE_INSTANCE, GEN_EDIT_STATE_MAIN, GEN_EDIT_STATE_MAIN_INHERITED)

MAKE_NATIVE_TYPE_FACTORY(InputEvent)

MAKE_NATIVE_TYPE_FACTORY(InputEventMouseButton)

MAKE_NATIVE_TYPE_FACTORY(Texture2D)


#endif // GODOT_TYPES_GEN_H
