// This file is complitely generated

#ifndef GODOT_TYPES_GEN_H
#define GODOT_TYPES_GEN_H

#include "godot_types_macro.h"
#include "godot_all_includes.h"

MAKE_NATIVE_TYPE_FACTORY(Object)

MAKE_NATIVE_TYPE_FACTORY(Node)

MAKE_NATIVE_TYPE_FACTORY(CanvasItem)

MAKE_NATIVE_TYPE_FACTORY(Node2D)

MAKE_NATIVE_TYPE_FACTORY(Sprite2D)

MAKE_NATIVE_TYPE_FACTORY(Control)

MAKE_NATIVE_TYPE_FACTORY(Label)

MAKE_NATIVE_TYPE_FACTORY(Viewport)

MAKE_NATIVE_TYPE_FACTORY(Window)

MAKE_NATIVE_TYPE_FACTORY(Resource)

MAKE_NATIVE_TYPE_FACTORY(InputEvent)

MAKE_NATIVE_TYPE_FACTORY(InputEventMouseButton)

MAKE_NATIVE_TYPE_FACTORY(Texture2D)


#endif // GODOT_TYPES_GEN_H
